---
- hosts: localhost
  tasks:
    - name: get openssh-version
      command: ssh -V
      register: sshd_version_raw
      changed_when: false
      check_mode: false

    - name: parse openssh-version
      set_fact:
        sshd_version: "{{ sshd_version_raw.stderr | regex_replace('.*_([0-9]*.[0-9]).*', '\\1') }}"

    - name: set default for ssh_ciphers if not supplied
      include_tasks: crypto_ciphers.yml
      tags:
        - V-219307

        