---
- hosts:
    - localhost
  roles:
    - roles/ansible-role-ubuntu-stig-vanilla
    - roles/ansible-role-ubuntu-stig-hardening
  serial: 50
  become: yes
  #vars:
  #  - deployment_task: configure_apps.yml