- name: Install required packages
  apt:
    name:
      - audispd-plugins
    state: latest
  tags:
    - V-129153
    - V-219162

- name: The Ubuntu operating system audit event multiplexor must be configured to off-load audit logs onto a different system or storage media from the system being audited
  lineinfile:
    dest: /etc/audisp/audisp-remote.conf
    regexp: "^(#)?remote_server"
    line: "remote_server = {{ security_audisp_remote_server }}"
  notify:
    - restart auditd
  tags:
    - V-219162

- name: The Ubuntu operating system audit event multiplexor must be configured to off-load audit logs onto a different system or storage media from the system being audited
  lineinfile:
    dest: /etc/audisp/plugins.d/au-remote.conf
    regexp: "^(#)?active"
    line: "active = yes"
  notify:
    - restart auditd
  tags:
    - V-219162

- name: Change file permissions for Security Tools
  ansible.builtin.file:
    path: '{{ item }}'
    mode: '0755'
  loop:
    '{{ security_audit_tools }}'
  tags:
  - V-219195

- name: Change file permissions for Security Tools
  ansible.builtin.file:
    path: '{{ item }}'
    group: 'root'
  loop:
    '{{ security_audit_tools }}'
  tags:
  - V-219197